### ISSUE TITLE
Third party libraries are not committed to the git repo

### ISSUE THREAD

**Issue by lozen130** [qddegtya/Android_Screen_Stream#4]
```
sys.path.append(r'C:\\ddmlib.jar')
sys.path.append(r'C:\\guava17.jar')
sys.path.append(r'C:\\rt.jar')
```

The three 3rd party libraries (as shown above) are not committed to the source codes. Can you help commit them so that I can have a chance to run the codes? Thanks!

**Comment by qddegtya** [comment]
Please download these jar packages standalone, then import them~ :smile:
